name: Build sidekick-bin
on: [push]
jobs:
  run:
    name: Build
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [macos-latest, ubuntu-latest, windows-latest]
        ocaml-version: [ '4.09.0', '4.08.1', '4.06.1' ]
    steps:
    - uses: actions/checkout@master
    - uses: avsm/setup-ocaml@master
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - run: opam pin add sidekick.dev sidekick-bin.dev -n .
    - run: opam depext -yt sidekick-bin
    - run: opam install -t . --deps-only
    - run: opam exec -- dune build
    - run: opam exec -- dune runtest
    - uses: actions/upload-artifact@master
      with:
        name: sidekick-bin-${{ matrix.operating-system }}-${{ matrix.ocaml-version }}.exe
        path: _build/default/src/main/main.exe
